// Generated by Wrangler
// by running `wrangler types`

interface Env {
  rate_limiter: KVNamespace;
  GROQ_API_KEY: string;
  OPENAI_API_KEY: string;
  ANTHROPIC_API_KEY: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  R2_BUCKET: R2Bucket;
  DB: D1Database;
  VECTORIZE_INDEX: VectorizeIndex;
  AI: Ai;
  ASSETS: Fetcher;
}
